---
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(badger)
```

# rgplates 
`r badge_devel("adamkocsis/rgplates", "green")`
`r badge_cran_release("rgplates", "orange")`
`r badge_cran_download("rgplates", "grand-total", "yellow")`
`r badge_cran_checks("rgplates")`

R interface for the GPlates Web Service and Desktop Application 

(Ádám T. Kocsis and Nussaïbah B. Raja)

The purpose of the 'rgplates' package is to facilitate spatially explicit analyses of deep time paleoenvironmental/paleoecological research. 
Offline methods require the presence of the GPlates Desktop Application (https://www.gplates.org/).
The functions here were removed from the chronosphere R package (v0.4.1), for better compliance with UNIX-principles and more efficient distribution/development.



This R extension was supported by the FAU GeoZentrum Nordbayern and is developed under the umbrella of the DFG (Deutsche Forschungsgemeinschaft) Research Unit TERSANE2 (For 2332, TEmperature Related Stressors in ANcient Extinctions).

This is a beta version. 

See the blog entry below for an example application:

# Installing

While the initial submissions are getting processed, the package can be built usiung the source deposited on this repository.

```r
install.packages("https://github.com/adamkocsis/rgplates/raw/main/_archive/source/rgplates_0.1.0.tar.gz", repos=NULL, type="source")
```

