---
title: "Internals"
description: >
  Technial details of the package interals.
---
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
</script>


# Requirements

## Dependencies

- [sf](https://cran.r-project.org/package=sf) *(Simple features)*: `rgplates` depends on the `sf` package to handle vector spatial data, such as plates, present-day coastlines, and spatial data that have explict Coordinate Reference System information. 

## Imports

Functions reused from other packages (necessary in all cases):

- `methods::new()`: Used to create `platemodel` instances.
- `utils::flush.console()`: Used for console-feedback.

## Suggests

Functions from some packages that are used by some functions only (optional):

- [knitr](https://cran.r-project.org/package=knitr) and [rmarkdown](https://cran.r-project.org/package=rmarkdown): used for vignette creation.
- [geojsonsf](https://cran.r-project.org/package=geojsonsf): used by the **online method** of `reconstruct()` to read in the spatial output of the GWS. 
- [sp](https://cran.r-project.org/package=sp): optional output formats for vector spatial data.
- [chronosphere](https://cran.r-project.org/package=chronosphere): informal suggestion in help files for downloading `platemodel` instances.

* * *


# Function call graph

<pre class="mermaid">
flowchart LR

  classDef extern fill:#CCC
  classDef ui fill:#f96

  reconstruct-matrix-method-->IteratedPointReconstruction
  reconstruct-matrix-method-->reconstructGPlates
  reconstruct-sf-method-->reconstructGPlates
  reconstruct-character-method-->gplates_reconstruct_coastlines
  reconstruct-character-method-->gplates_reconstruct_static_polygons
  reconstruct-character-method-->reconstructGPlates
  reconstruct-Spatial-method-->reconstructGPlates
  reconstruct-sf-method-->reconstructGPlates

  subgraph front_end.R

  reconstruct:::ui-->reconstruct-matrix-method
  click reconstruct "../reference/reconstruct.html"
  reconstruct-->reconstruct-data.frame-method
  reconstruct-->reconstruct-numeric-method
  reconstruct-->reconstruct-character-method
  reconstruct-->reconstruct-Spatial-method
  reconstruct-->reconstruct-sf-method
  reconstruct-data.frame-method-->reconstruct-matrix-method
  reconstruct-numeric-method-->reconstruct-matrix-method

  end


  reconstructGPlates-->getOS
  reconstructGPlates-->st_as_sf
  reconstructGPlates-->st_transform
  reconstructGPlates-->st_crs
  reconstructGPlates-->randomString
  reconstructGPlates-->st_write
  reconstructGPlates-->st_read
  reconstructGPlates-->st_as_Spatial
  reconstructGPlates-->st_coordinates
  reconstructGPlates-->fileFromPath

  subgraph offline.R

  reconstructGPlates-->testGPlates
  reconstructGPlates-->winDefaultGPlates
  reconstructGPlates-->macDefaultGPlates
  
  end

  gplates_reconstruct_coastlines-->geojson_sf
  gplates_reconstruct_static_polygons-->geojson_sf

  subgraph online.R

  gplates_reconstruct_static_polygons
  gplates_reconstruct_coastlines
  IteratedPointReconstruction-->gplates_reconstruct_points
  gplates_reconstruct_points

  end
  
  mapedge:::ui-->SpatialPolygons
  click mapedge "../reference/mapedge.html"
  mapedge-->Polygons
  mapedge-->CRS
  mapedge-->st_geometry
  mapedge-->st_polygon

  subgraph utility.R

  mapedge
  getOS
  fileFromPath
  randomString
  mapedge-->detailedBounds
  
  end

  platemodel-show-->fileFromPath

  subgraph platemodel.R
  platemodel-classdef
  platemodel-initialize:::ui
  click platemodel-initialize "../reference/platemodel.html"
  platemodel-show
  end

  subgraph EXT[EXTERNALS]
	subgraph sf

	st_as_sf:::extern
	st_transform:::extern
	st_crs:::extern
	st_write:::extern
	st_read:::extern
	st_as_Spatial:::extern
	st_coordinates:::extern
	st_geometry:::extern
	st_polygon:::extern

	end

	subgraph sp
	CRS:::extern
	Polygons:::extern
	SpatialPolygons:::extern
	end

	subgraph geojsonsf
	geojson_sf:::extern
	end
  end
  
  style EXT fill:#eee,border:#bbb

</pre>
